/* #undef AC_APPLE_UNIVERSAL_BUILD */
/* #undef CRAY_STACKSEG_END */
/* #undef C_ALLOCA */
#define GET0SIG_CONST_T const
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
/* #undef HAVE_CRYPTO_THREADID */
/* #undef HAVE_CRYPTO_THREADID_GET_CALLBACK */
/* #undef HAVE_CRYPTO_THREADID_SET_CALLBACK */
#define HAVE_ERR_REMOVE_STATE 1
#define HAVE_ERR_REMOVE_THREAD_STATE 1
#define HAVE_EVP_BLAKE2B512 1
#define HAVE_EVP_BLAKE2S256 1
#define HAVE_EVP_CIPHER_CTX_RESET 1
#define HAVE_EVP_MD_CTX_FREE 1
#define HAVE_EVP_SHA3_224 1
#define HAVE_EVP_SHA3_256 1
#define HAVE_EVP_SHA3_384 1
#define HAVE_EVP_SHA3_512 1
#define HAVE_FCNTL_H 1
#define HAVE_HMAC_CTX_FREE 1
#define HAVE_HMAC_CTX_NEW 1
#define HAVE_H_ERRNO 1
#define HAVE_I2D_RE_X509_TBS 1
#define HAVE_INTTYPES_H 1
/* #undef HAVE_KSECCLASS */
/* #undef HAVE_LIBCRYPT32 */
/* #undef HAVE_LIBCRYPTO */
/* #undef HAVE_LIBGDI32 */
/* #undef HAVE_LIBPTHREAD */
/* #undef HAVE_LIBPTHREADGC */
/* #undef HAVE_LIBPTHREADGC2 */
/* #undef HAVE_LIBSSL */
/* #undef HAVE_LIBWS2_32 */
#define HAVE_MEMORY_H 1
/* #undef HAVE_OPENSSL_INIT_SSL */
#define HAVE_OPENSSL_KDF_H 1
/* #undef HAVE_OPENSSL_SSL_H */
#define HAVE_OPENSSL_VERSION 1
/* #undef HAVE_OPENSSL_ZALLOC */
/* #undef HAVE_SECURITY_SECURITY_H */
#define HAVE_SOCKLEN_T 1
#define HAVE_SSL_CTX_SET_ALPN_PROTOS 1
/* #undef HAVE_SSL_LIBRARY_INIT */
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TIMEGM 1
#define HAVE_UNISTD_H 1
#define HAVE_X509_CHECK_HOST 1
#define HAVE_X509_CRL_DIGEST 1
#define HAVE_X509_CRL_GET0_SIGNATURE 1
#define HAVE_X509_DIGEST 1
#define HAVE_X509_GET0_NOTAFTER 1
#define HAVE_X509_GET0_NOTBEFORE 1
#define HAVE_X509_GET0_SIGNATURE 1
#define HAVE_X509_STORE_CTX_GET0_CHAIN 1
/* #undef HAVE_X509_VERIFY_PARAM_ID */
/* #undef O_PLMT */
/* #undef PACKAGE_BUGREPORT */
/* #undef PACKAGE_NAME */
/* #undef PACKAGE_STRING */
/* #undef PACKAGE_TARNAME */
/* #undef PACKAGE_URL */
/* #undef PACKAGE_VERSION */
/* #undef STACK_DIRECTION */
/* #undef STDC_HEADERS */
#define SYSTEM_CACERT_FILENAME "/etc/ssl/certs/ca-certificates.crt"
/* #undef WORDS_BIGENDIAN */
/* #undef _REENTRANT */
/* #undef size_t */
