/* #undef HAVE_DECL_RL_DONE */
/* #undef HAVE_LIBNCURSES */
/* #undef HAVE_LIBNCURSESW */
/* #undef HAVE_LIBREADLINE */
#define HAVE_POLL
#define HAVE_POLL_H
#define HAVE_READLINE_HISTORY_H
#define HAVE_READLINE_READLINE_H
#define HAVE_RL_CLEANUP_AFTER_SIGNAL
#define HAVE_RL_CLEAR_PENDING_INPUT
#define HAVE_RL_COMPLETION_MATCHES
#define HAVE_RL_DONE
#define HAVE_RL_EVENT_HOOK
#define HAVE_RL_FILENAME_COMPLETION_FUNCTION
#define HAVE_RL_INSERT_CLOSE 1
#define HAVE_RL_READLINE_STATE
/* #undef HAVE_RL_SET_KEYBOARD_INPUT_TIMEOUT */
#define HAVE_RL_SET_PROMPT
/* #undef O_PLMT */
/* #undef _REENTRANT */
