# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_ <- function(argv0) {
    .Call(`_rolog_init_`, argv0)
}

done_ <- function() {
    .Call(`_rolog_done_`)
}

consult_ <- function(files) {
    .Call(`_rolog_consult_`, files)
}

call_ <- function(lang) {
    .Call(`_rolog_call_`, lang)
}

findall_ <- function(lang) {
    .Call(`_rolog_findall_`, lang)
}

