# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.init <- function(argv0) {
    .Call('_rolog_init_', PACKAGE = 'rolog', argv0)
}

.done <- function() {
    .Call('_rolog_done_', PACKAGE = 'rolog')
}

.consult <- function(files) {
    .Call('_rolog_consult_', PACKAGE = 'rolog', files)
}

.once <- function(query) {
    .Call('_rolog_once_', PACKAGE = 'rolog', query)
}

.findall <- function(query) {
    .Call('_rolog_findall_', PACKAGE = 'rolog', query)
}

.portray <- function(query) {
    .Call('_rolog_portray_', PACKAGE = 'rolog', query)
}

