# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.consult <- function(files) {
    .Call('_rolog_consult_', PACKAGE = 'rolog', files)
}

.query <- function(query, options) {
    .Call('_rolog_query_', PACKAGE = 'rolog', query, options)
}

.clear <- function() {
    .Call('_rolog_clear_', PACKAGE = 'rolog')
}

.submit <- function() {
    .Call('_rolog_submit_', PACKAGE = 'rolog')
}

.once <- function(query, options) {
    .Call('_rolog_once_', PACKAGE = 'rolog', query, options)
}

.findall <- function(query, options) {
    .Call('_rolog_findall_', PACKAGE = 'rolog', query, options)
}

.portray <- function(query, options) {
    .Call('_rolog_portray_', PACKAGE = 'rolog', query, options)
}

.init <- function(argv0) {
    .Call('_rolog_init_', PACKAGE = 'rolog', argv0)
}

.done <- function() {
    .Call('_rolog_done_', PACKAGE = 'rolog')
}

